Add Firefox
danielopez26/TrainingQA pull request #4
Opened 2021-09-10 16:32 UTC by danielopez26

2021-09-10 21:01 UTC, aperdomob requested changes
Do you execute both browsers in your CI?

2021-09-10 21:25 UTC, danielopez26 commented
Yes, I have defined both controllers and run each of them

2021-09-13 22:29 UTC, aperdomob requested changes

2021-09-13 22:29 UTC, aperdomob commented on src/main/java/GoogleSearch.java
> +public class GoogleSearch {
you don't need this class

2021-09-13 22:29 UTC, aperdomob commented on src/main/java/drivers/Drivers.java
> +    WebDriver driver;
don't use global variable

2021-09-13 22:29 UTC, aperdomob commented on src/main/java/drivers/Drivers.java
> +    public String BROWSER = System.getProperty("BROWSER", "Firefox");
this class should not have this logic, also use camel case to name of variables

2021-09-14 16:41 UTC, aperdomob requested changes

2021-09-14 16:41 UTC, aperdomob commented on src/main/java/drivers/Drivers.java
> +                return chromeDriver;
Don't create the `WebDriver chromeDriver` only return the new instance

```java
return new ChromeDriver();
```

2021-09-14 16:41 UTC, aperdomob commented on src/main/java/drivers/Drivers.java
> +                return firefoxDriver;
same comment here

2021-09-14 16:52 UTC, aperdomob approved these changes

2021-09-14 16:53 UTC, merged