Implementation of POM
danielopez26/TrainingQA pull request #6
Opened 2021-09-17 15:02 UTC by danielopez26

2021-09-20 16:06 UTC, danielopez26 commented
I am returning a boolean as my validation but I have a doubt about it, where do I put my assert? in a Test class?

So far, I'm working to simplify the code even more.

2021-09-20 16:53 UTC, danielopez26 commented
I have modified my test, I get a string from the payment class and I validate it in my test

2021-09-20 17:55 UTC, aperdomob requested changes
recuerde agregarle private a todos las variables de las clases

2021-09-20 17:55 UTC, aperdomob commented on src/main/java/pagesObject/SignInPage.java
> +    public void login (){
the user and password should be input parameters

2021-09-20 17:55 UTC, aperdomob commented on src/test/java/TestAutomationPractice.java
> +    PaymentPage paymentPage = new PaymentPage(driver);
instance all variables into before

2021-09-20 17:55 UTC, aperdomob commented on src/test/java/TestAutomationPractice.java
> +        homePage.addToCart();
que estas agregando, sea más explicito en el nombre del metodo para que saber si agregas un vestion, pantalon, blusa, etc

2021-09-21 15:56 UTC, aperdomob requested changes

2021-09-21 15:56 UTC, aperdomob commented on src/test/java/TestAutomationPractice.java
> +    PaymentPage paymentPage;
add private

2021-09-21 17:05 UTC, danielopez26 commented
Added private

2021-09-22 19:55 UTC, aperdomob approved these changes

2021-09-22 19:55 UTC, merged